backend:
  #runs before each test
  stages:
    - Build
  # Before script runs go to backend directory and 'clean installs'
  before_script:
    - cd backend
    - npm ci
  #Checks if the backend builds
  Build:
    stage: Build
  script:
    - npm run dev


frontend:
  stages:
   - Build