image: node:latest

stages:
  - Lint
  - Build
  - Test

backend:lint:
  stage: Lint
  before_script:
    - cd backend
    - npm run lint

backend:build:
  stage: Build
  before_script:
    - cd backend
    - npm ci
  script:
    - npm run build

backend:test:
  stage: Test
  before_script:
    - cd backend
    - npm ci
  script:
    - npm test

frontend:lint:
  stage: Lint
  before_script:
    - cd frontend
    - npm run lint

frontend:build:
  stage: Build
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build

frontend:test:
  stage: Test
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm test
