stages:
  - build
  - test


backend:
  image: node:slim
  #Checks if the backend builds
  stage: build
  script:
    - cd backend
    - npm run
    - npm ci


frontend:
  image: node:slim
  #Checks if the frontend builds
  stage: build
  script:
    - cd frontend
    - npm ci
    - npm run