services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - sqlite-db:/database
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"

  database:
    build:
      context: ./database
    volumes:
      - sqlite-db:/database

  ai_service:
    build:
      context: ./ai_service_chat
      dockerfile: Dockerfile
    container_name: ai_service
    env_file:
      - ./ai_service_chat/.env
    ports:
      - "8000:8000"

volumes:
  sqlite-db: