services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - hr-forecasting
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"

  database:
    extends:
      file: ./database/docker-compose.postgres.yml
      service: postgres

networks:
  hr-forecasting:

volumes:
  postgres_data: