services:
  db:
    image: postgres:16
    restart: always
    container_name: project_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-net

  migrations:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/appdb?schema=public"
    command: >
      sh -c "npx prisma migrate dev && npx prisma generate"
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  db_data:
